export const obj = [
  {
    checked: null,
    children: [
      {
        checked: 'true',
        children: null,
        cname: '用户画像',
        createdate: null,
        creator: null,
        flag: 0,
        icon: '',
        id: 124877,
        modelpage: '#/dmp/dmpuserinfo',
        pid: 124876,
        proid: 23,
        realname: null,
        redirect: null,
        rel: null,
        sortid: 1,
        updatedate: null,
        updator: null
      },
      {
        checked: null,
        children: null,
        cname: '盗墓片',
        createdate: null,
        creator: null,
        flag: 0,
        icon: '',
        id: 125008,
        modelpage: '#/dmp/dmpTagManage',
        pid: 124876,
        proid: 23,
        realname: null,
        redirect: '<null>',
        rel: null,
        sortid: 1,
        updatedate: null,
        updator: null
      },
      {
        checked: null,
        children: null,
        cname: '用户群像',
        createdate: null,
        creator: null,
        flag: 0,
        icon: '',
        id: 124928,
        modelpage: '#/dmp/dmpusermark',
        pid: 124876,
        proid: 23,
        realname: null,
        redirect: null,
        rel: null,
        sortid: 2,
        updatedate: null,
        updator: null
      },
      {
        checked: null,
        children: null,
        cname: 'Ti推荐标签统计',
        createdate: null,
        creator: null,
        flag: 0,
        icon: '',
        id: 124947,
        modelpage: '#/dmp/tiRecommend',
        pid: 124876,
        proid: 23,
        realname: null,
        redirect: null,
        rel: null,
        sortid: 3,
        updatedate: null,
        updator: null
      }
    ],
    cname: 'DMP',
    createdate: null,
    creator: null,
    flag: 0,
    icon: '',
    id: 124876,
    modelpage: null,
    pid: 0,
    proid: 23,
    realname: null,
    redirect: null,
    rel: null,
    sortid: 1,
    updatedate: null,
    updator: null
  },
  {
    checked: null,
    children: [
      {
        checked: 'true',
        children: null,
        cname: '新闻全标签',
        createdate: null,
        creator: null,
        flag: 0,
        icon: '',
        id: 124891,
        modelpage: '#/tag/tn2Search',
        pid: 124890,
        proid: 23,
        realname: null,
        redirect: null,
        rel: null,
        sortid: 1,
        updatedate: null,
        updator: null
      },
      {
        checked: null,
        children: null,
        cname: '新闻粗标签',
        createdate: null,
        creator: null,
        flag: 0,
        icon: '',
        id: 124897,
        modelpage: '#/tag/tnSearch',
        pid: 124890,
        proid: 23,
        realname: null,
        redirect: null,
        rel: null,
        sortid: 2,
        updatedate: null,
        updator: null
      },
      {
        checked: null,
        children: null,
        cname: '新闻打标签统计',
        createdate: null,
        creator: null,
        flag: 0,
        icon: '',
        id: 124916,
        modelpage: '#/tag/newsSignTag',
        pid: 124890,
        proid: 23,
        realname: null,
        redirect: null,
        rel: null,
        sortid: 3,
        updatedate: null,
        updator: null
      },
      {
        checked: null,
        children: null,
        cname: '视频全标签',
        createdate: null,
        creator: null,
        flag: 0,
        icon: '',
        id: 124906,
        modelpage: '#/tag/videoSearch',
        pid: 124890,
        proid: 23,
        realname: null,
        redirect: null,
        rel: null,
        sortid: 4,
        updatedate: null,
        updator: null
      },
      {
        checked: null,
        children: null,
        cname: '视频粗标签',
        createdate: null,
        creator: null,
        flag: 0,
        icon: '',
        id: 124911,
        modelpage: '#/tag/videoLevelSearch',
        pid: 124890,
        proid: 23,
        realname: null,
        redirect: null,
        rel: null,
        sortid: 5,
        updatedate: null,
        updator: null
      },
      {
        checked: null,
        children: null,
        cname: '视频打标签统计',
        createdate: null,
        creator: null,
        flag: 0,
        icon: '',
        id: 124920,
        modelpage: '#/tag/videoSignTag',
        pid: 124890,
        proid: 23,
        realname: null,
        redirect: null,
        rel: null,
        sortid: 6,
        updatedate: null,
        updator: null
      },
      {
        checked: null,
        children: null,
        cname: '小视频全标签',
        createdate: null,
        creator: null,
        flag: 0,
        icon: '',
        id: 125642,
        modelpage: '#/tag/miniVideoSearch',
        pid: 124890,
        proid: 23,
        realname: null,
        redirect: '<null>',
        rel: null,
        sortid: 6.5,
        updatedate: null,
        updator: null
      },
      {
        checked: null,
        children: null,
        cname: '小视频粗标签',
        createdate: null,
        creator: null,
        flag: 0,
        icon: '',
        id: 125643,
        modelpage: '#/tag/miniVideoLevelSearch',
        pid: 124890,
        proid: 23,
        realname: null,
        redirect: '<null>',
        rel: null,
        sortid: 7,
        updatedate: null,
        updator: null
      },
      {
        checked: null,
        children: null,
        cname: '小视频打标签统计',
        createdate: null,
        creator: null,
        flag: 0,
        icon: '',
        id: 125810,
        modelpage: '#/tag/miniNewsSignTag',
        pid: 124890,
        proid: 23,
        realname: null,
        redirect: '<null>',
        rel: null,
        sortid: 8,
        updatedate: null,
        updator: null
      }
    ],
    cname: '标签内容',
    createdate: null,
    creator: null,
    flag: 0,
    icon: '',
    id: 124890,
    modelpage: null,
    pid: 0,
    proid: 23,
    realname: null,
    redirect: null,
    rel: null,
    sortid: 2,
    updatedate: null,
    updator: null
  },
  {
    checked: null,
    children: [
      {
        checked: 'true',
        children: null,
        cname: 'URL查询',
        createdate: null,
        creator: null,
        flag: 0,
        icon: '',
        id: 124903,
        modelpage: '#/url/urlSearch',
        pid: 124902,
        proid: 23,
        realname: null,
        redirect: null,
        rel: null,
        sortid: 1,
        updatedate: null,
        updator: null
      }
    ],
    cname: 'URL内容',
    createdate: null,
    creator: null,
    flag: 0,
    icon: '',
    id: 124902,
    modelpage: null,
    pid: 0,
    proid: 23,
    realname: null,
    redirect: null,
    rel: null,
    sortid: 3,
    updatedate: null,
    updator: null
  },
  {
    checked: null,
    children: [
      {
        checked: null,
        children: null,
        cname: '用户画像',
        createdate: null,
        creator: null,
        flag: 0,
        icon: '',
        id: 124958,
        modelpage: '#/zhangyu/userInfo',
        pid: 124957,
        proid: 23,
        realname: null,
        redirect: '<null>',
        rel: null,
        sortid: 1,
        updatedate: null,
        updator: null
      }
    ],
    cname: '章鱼输入法',
    createdate: null,
    creator: null,
    flag: 0,
    icon: '',
    id: 124957,
    modelpage: null,
    pid: 0,
    proid: 23,
    realname: null,
    redirect: '<null>',
    rel: null,
    sortid: 3,
    updatedate: null,
    updator: null
  }
];
